builds:
  - binary: systrayhelper
    env: # cgo can be off, the syscall.LoadLazy from the embedded data doesn't need it
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - 386
  - binary: systrayhelper
    env: # cgo is needed on linux to link against libgtk-3-dev and libappindicator3-dev
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
checksum:
  name_template: "checksums_winAndLinux.txt"
archive:
  format_overrides:
    - goos: windows
      format: zip

# TODO: scoop generator https://goreleaser.com/scoop/