os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libgtk-3-dev
      - libappindicator3-dev

language: go

go:
  - "1.x"
  - "1.9.x"
  - "1.10.x"
  - master

matrix:
  allow_failures:
    - go: master

go_import_path: github.com/ssbc/systrayhelper

install:
  - go get -t -v github.com/ssbc/systrayhelper/...
