os:
  - linux
  - osx

addons:
  apt:
    packages:
      - xvfb
      - libgtk-3-dev
      - libappindicator3-dev

language: go

go:
  - "1.x"
  - "1.9.x"
  - "1.10.x"
  - master

matrix:
  allow_failures:
    - go: master

go_import_path: github.com/ssbc/systrayhelper

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=':99.0' && Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &; fi
  - go get -t -v github.com/ssbc/systrayhelper/...
