os:
  - linux
  - osx

addons:
  apt:
    packages:
      - xvfb
      - libgtk-3-dev
      - libappindicator3-dev

language: go

go:
  - "1.x"
  - "1.7.x"
  - "1.10.x"
  - master

matrix:
  allow_failures:
    - go: master

go_import_path: github.com/ssbc/systrayhelper

install:
  - ./.travis.install.sh

script:
  - ./.travis.runtest.sh

after_success:
    - test -n "$TRAVIS_TAG" && bash .gorelease.sh
