os:
  - linux
  - osx

addons:
  apt:
    packages:
      - xvfb
      - xdotool
      - i3
      - libgtk-3-dev
      - libappindicator3-dev
      - rpm

language: go

go:
  - "1.x"
  - "1.7.x"
  - "1.10.x"
  - master

# passed two times except osx w/ go 1.7
# https://travis-ci.org/ssbc/systrayhelper/builds/402264830
# https://travis-ci.org/ssbc/systrayhelper/builds/402261541
matrix:
  allow_failures:
    - go: master
    - go: "1.7.x"

go_import_path: github.com/ssbc/systrayhelper

install: ./.travis.install.sh
script: ./.travis.runtest.sh

deploy:
- provider: script
  skip_cleanup: true
  # maybe update curl -sL https://git.io/goreleaser > .goreleaser.sh
  script: bash .goreleaser.sh
  on:
    tags: true
    go: "1.10.x"


# food for thought: complex example: https://github.com/tsuru/tsuru/blob/master/.travis.yml
