# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/getlantern/context";
    fetch = {
      type = "git";
      url = "https://github.com/getlantern/context";
      rev = "624d99b1798d7c5375ea1d3ca4c5b04d58f7c775";
      sha256 = "09yf9x6478a5z01hybr98zwa8ax3fx7l6wwsvdkxp3fdg9dqm13b";
    };
  }
  {
    goPackagePath = "github.com/getlantern/errors";
    fetch = {
      type = "git";
      url = "https://github.com/getlantern/errors";
      rev = "e9c0296368b736086adb20832549567064224854";
      sha256 = "0x00iqkwp5m09z49lxiczmbs2synij2s11imay44fip3133kgi8i";
    };
  }
  {
    goPackagePath = "github.com/getlantern/golog";
    fetch = {
      type = "git";
      url = "https://github.com/getlantern/golog";
      rev = "cca714f7feb5df8e455f409b549d384441ac4578";
      sha256 = "0gnf30n38zkx356cqc6jdv1kbzy59ddqhqndwrxsm2n2zc3b5p7q";
    };
  }
  {
    goPackagePath = "github.com/getlantern/hex";
    fetch = {
      type = "git";
      url = "https://github.com/getlantern/hex";
      rev = "083fba3033ad473db3dd31c9bb368473d37581a7";
      sha256 = "18q6rypmcqmcwlfzrrdcz08nff0a289saplvd9y3ifnfcqdw3j77";
    };
  }
  {
    goPackagePath = "github.com/getlantern/hidden";
    fetch = {
      type = "git";
      url = "https://github.com/getlantern/hidden";
      rev = "d52a649ab33af200943bb599898dbdcfdbc94cb7";
      sha256 = "0133qmp4sjq8da5di3459vc5g5nqbpqra0f558zd95js3fdmkmsi";
    };
  }
  {
    goPackagePath = "github.com/getlantern/ops";
    fetch = {
      type = "git";
      url = "https://github.com/getlantern/ops";
      rev = "37353306c90844c8e0591956f56611f46299d202";
      sha256 = "0q8j2963jqf3p7fcnsfinkvz71mfylrkk2xjar775zjx5a23sa5i";
    };
  }
  {
    goPackagePath = "github.com/getlantern/stack";
    fetch = {
      type = "git";
      url = "https://github.com/getlantern/stack";
      rev = "02f928aad224fbccd50d66edd776fc9d1e9f2f2b";
      sha256 = "0ddl5r4iw3c7p4drh4d8phl7d0ssdddsnd3xjm1lzgxylqq6r568";
    };
  }
  {
    goPackagePath = "github.com/getlantern/systray";
    fetch = {
      type = "git";
      url = "https://github.com/getlantern/systray";
      rev = "62af9eb8030c168caa78856c967e6d2c4a7d813e";
      sha256 = "0ix2h0visj0d0k4zvx2wxg1qjih229c6pnxlg25ihajd33izf1bc";
    };
  }
  {
    goPackagePath = "github.com/oxtoacart/bpool";
    fetch = {
      type = "git";
      url = "https://github.com/oxtoacart/bpool";
      rev = "4e1c5567d7c2dd59fa4c7c83d34c2f3528b025d6";
      sha256 = "01kk6dhkz96yhp3p5v2rjwq8mbrwrdsn6glqw7jp4h7g5za7yi95";
    };
  }
]
