[[constraint]]
  branch = "master"
  name = "github.com/getlantern/systray"

# testing
[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true

